//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccomplishmentState
    {
        public long ID { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<byte> SubType { get; set; }
        public long EntityID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime EditedOn { get; set; }
        public string EditedBy { get; set; }
        public string IpAddress { get; set; }
        public byte Status { get; set; }
        public long AccomplishmentID { get; set; }
        public string Description { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual EntityAwardAndCompletion EntityAwardAndCompletion { get; set; }
    }
}
