//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppreciationAndRecommendation
    {
        public AppreciationAndRecommendation()
        {
            this.AppreciationAndRecommendationParticipants = new HashSet<AppreciationAndRecommendationParticipant>();
            this.AppreciationAndRecommendationSkills = new HashSet<AppreciationAndRecommendationSkill>();
            this.Notificactions = new HashSet<Notificaction>();
        }
    
        public long ReferenceID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public long EntityID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime EditedOn { get; set; }
        public string EditedBy { get; set; }
        public string IpAddress { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<long> AwardID { get; set; }
        public byte Type { get; set; }
        public Nullable<long> CareerHistoryID { get; set; }
        public Nullable<long> SourceEntityID { get; set; }
        public string RecomedationRelation { get; set; }
    
        public virtual ICollection<AppreciationAndRecommendationParticipant> AppreciationAndRecommendationParticipants { get; set; }
        public virtual ICollection<AppreciationAndRecommendationSkill> AppreciationAndRecommendationSkills { get; set; }
        public virtual EntityAwardAndCompletion EntityAwardAndCompletion { get; set; }
        public virtual ICollection<Notificaction> Notificactions { get; set; }
    }
}
