//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppreciationAndRecommendationSkill
    {
        public long ID { get; set; }
        public long EntitySkillID { get; set; }
        public long ReferenceID { get; set; }
    
        public virtual AppreciationAndRecommendation AppreciationAndRecommendation { get; set; }
        public virtual EntitySkill EntitySkill { get; set; }
    }
}
