//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Association
    {
        public long AssociationID { get; set; }
        public Nullable<long> EntityID { get; set; }
        public Nullable<long> EntityID2 { get; set; }
        public Nullable<byte> AssociationType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<byte> ObjectStatus { get; set; }
        public string IpAddress { get; set; }
        public Nullable<long> OppositeRowID { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Entity Entity1 { get; set; }
    }
}
