//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AwardSkill
    {
        public long AwardSkillID { get; set; }
        public long AwardID { get; set; }
        public long EntitySkillID { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual EntityAwardAndCompletion EntityAwardAndCompletion { get; set; }
        public virtual EntitySkill EntitySkill { get; set; }
    }
}
