//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareerHistory
    {
        public CareerHistory()
        {
            this.CareerHistorySkills = new HashSet<CareerHistorySkill>();
            this.EntityAwardAndCompletions = new HashSet<EntityAwardAndCompletion>();
            this.NetworkActivities = new HashSet<NetworkActivity>();
        }
    
        public long CareerHistoryID { get; set; }
        public long EntityID { get; set; }
        public long JobTitleID { get; set; }
        public Nullable<long> OrganizationID { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<int> StartFromMonth { get; set; }
        public Nullable<int> StartFromYear { get; set; }
        public Nullable<int> StartFromDay { get; set; }
        public Nullable<int> EndFromDay { get; set; }
        public Nullable<int> EndFromMonth { get; set; }
        public Nullable<int> EndFromYear { get; set; }
        public string About { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<System.DateTime> PottentialStartDate { get; set; }
        public Nullable<System.DateTime> PottentialEndDate { get; set; }
        public Nullable<bool> PottentialCurrent { get; set; }
        public string SubType { get; set; }
        public Nullable<bool> Confidential { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual JobTitle JobTitle { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<CareerHistorySkill> CareerHistorySkills { get; set; }
        public virtual ICollection<EntityAwardAndCompletion> EntityAwardAndCompletions { get; set; }
        public virtual ICollection<NetworkActivity> NetworkActivities { get; set; }
    }
}
