//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatGroupMessageListener
    {
        public long ID { get; set; }
        public Nullable<long> MessageID { get; set; }
        public Nullable<long> EntityID { get; set; }
        public Nullable<bool> Listning { get; set; }
        public Nullable<byte> MessageStatus { get; set; }
    
        public virtual ChatGroupMessage ChatGroupMessage { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
