//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatGroup
    {
        public ChatGroup()
        {
            this.ChatGroupMessages = new HashSet<ChatGroupMessage>();
            this.ChatGroupUsers = new HashSet<ChatGroupUser>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> LoginRequired { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string ImagePath { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> GroupType { get; set; }
        public string Url { get; set; }
    
        public virtual ICollection<ChatGroupMessage> ChatGroupMessages { get; set; }
        public virtual ICollection<ChatGroupUser> ChatGroupUsers { get; set; }
    }
}
