//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatGroupMessage
    {
        public ChatGroupMessage()
        {
            this.ChatGroupMessageListeners = new HashSet<ChatGroupMessageListener>();
        }
    
        public long ID { get; set; }
        public string Message { get; set; }
        public long EntityID { get; set; }
        public long GroupID { get; set; }
        public int MessageType { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int Status { get; set; }
    
        public virtual ChatGroup ChatGroup { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual ICollection<ChatGroupMessageListener> ChatGroupMessageListeners { get; set; }
    }
}
