//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatGroupUser
    {
        public long ID { get; set; }
        public long GroupID { get; set; }
        public Nullable<long> EntityID { get; set; }
        public System.DateTime LastOnline { get; set; }
        public int Type { get; set; }
    
        public virtual ChatGroup ChatGroup { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
