//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentComment
    {
        public long CommentID { get; set; }
        public Nullable<int> CommentType { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
        public Nullable<long> EntityID { get; set; }
        public Nullable<bool> Active { get; set; }
        public byte ObjectStatus { get; set; }
    
        public virtual Master_CommentType Master_CommentType { get; set; }
        public virtual ObjectStatu ObjectStatu { get; set; }
    }
}
