//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public long ContentID { get; set; }
        public int ContentType { get; set; }
        public long EntityID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime PostedOn { get; set; }
        public Nullable<System.DateTime> PublishOn { get; set; }
        public string IPAddress { get; set; }
    
        public virtual Master_ContentType Master_ContentType { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
