//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityMedia
    {
        public long EntityID { get; set; }
        public string Path { get; set; }
        public byte MediaType { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual Entity Entity { get; set; }
    }
}
