//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityAwardParticipant
    {
        public long EntityAwardID { get; set; }
        public long EntityID { get; set; }
        public long ID { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<long> RefrenceEntity { get; set; }
        public string Role { get; set; }
        public string GroupID { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Entity Entity1 { get; set; }
        public virtual EntityAwardAndCompletion EntityAwardAndCompletion { get; set; }
    }
}
