//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntitySearch
    {
        public long ID { get; set; }
        public string Keyword { get; set; }
        public Nullable<long> EntityID { get; set; }
        public string Url { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte Status { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long SourceEntity { get; set; }
        public Nullable<long> Score { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Entity Entity1 { get; set; }
        public DateTime EditedOn { get; set; }
    }
}
