//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public Entity()
        {
            this.AccomplishmentStates = new HashSet<AccomplishmentState>();
            this.Addresses = new HashSet<Address>();
            this.AppreciationAndRecommendationParticipants = new HashSet<AppreciationAndRecommendationParticipant>();
            this.Associations = new HashSet<Association>();
            this.Associations1 = new HashSet<Association>();
            this.CareerHistories = new HashSet<CareerHistory>();
            this.ChatGroupMessages = new HashSet<ChatGroupMessage>();
            this.ChatGroupMessageListeners = new HashSet<ChatGroupMessageListener>();
            this.ChatGroupUsers = new HashSet<ChatGroupUser>();
            this.Contents = new HashSet<Content>();
            this.Emails = new HashSet<Email>();
            this.EntityAwardAndCompletions = new HashSet<EntityAwardAndCompletion>();
            this.EntityAwardParticipants = new HashSet<EntityAwardParticipant>();
            this.EntityAwardParticipants1 = new HashSet<EntityAwardParticipant>();
            this.EntityMedias = new HashSet<EntityMedia>();
            this.EntitySkills = new HashSet<EntitySkill>();
            this.EntitySkillStates = new HashSet<EntitySkillState>();
            this.EntityWidgets = new HashSet<EntityWidget>();
            this.GeneralSettings = new HashSet<GeneralSetting>();
            this.IntelligenceActions = new HashSet<IntelligenceAction>();
            this.JobSearchSettings = new HashSet<JobSearchSetting>();
            this.NetworkSettings = new HashSet<NetworkSetting>();
            this.NotificationSubscribers = new HashSet<NotificationSubscriber>();
            this.Organizations = new HashSet<Organization>();
            this.People = new HashSet<Person>();
            this.Phones = new HashSet<Phone>();
            this.Posts = new HashSet<Post>();
            this.PostInteractions = new HashSet<PostInteraction>();
            this.PostReplyInteractions = new HashSet<PostReplyInteraction>();
            this.PrivacySettings = new HashSet<PrivacySetting>();
            this.SubscriptionHistories = new HashSet<SubscriptionHistory>();
            this.EntitySearches = new HashSet<EntitySearch>();
            this.EntitySearches1 = new HashSet<EntitySearch>();
            this.PostTags = new HashSet<PostTag>();
            this.ActivityActions = new HashSet<ActivityAction>();
            this.NetworkActivities = new HashSet<NetworkActivity>();
            this.EntityImports = new HashSet<EntityImport>();
            this.PostInteractions1 = new HashSet<PostInteraction>();
            this.EntityStates = new HashSet<EntityState>();
            this.EntityStates1 = new HashSet<EntityState>();
        }
    
        public long EntityID { get; set; }
        public int EntityType { get; set; }
    
        public virtual ICollection<AccomplishmentState> AccomplishmentStates { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<AppreciationAndRecommendationParticipant> AppreciationAndRecommendationParticipants { get; set; }
        public virtual ICollection<Association> Associations { get; set; }
        public virtual ICollection<Association> Associations1 { get; set; }
        public virtual ICollection<CareerHistory> CareerHistories { get; set; }
        public virtual ICollection<ChatGroupMessage> ChatGroupMessages { get; set; }
        public virtual ICollection<ChatGroupMessageListener> ChatGroupMessageListeners { get; set; }
        public virtual ICollection<ChatGroupUser> ChatGroupUsers { get; set; }
        public virtual ICollection<Content> Contents { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<EntityAwardAndCompletion> EntityAwardAndCompletions { get; set; }
        public virtual ICollection<EntityAwardParticipant> EntityAwardParticipants { get; set; }
        public virtual ICollection<EntityAwardParticipant> EntityAwardParticipants1 { get; set; }
        public virtual ICollection<EntityMedia> EntityMedias { get; set; }
        public virtual ICollection<EntitySkill> EntitySkills { get; set; }
        public virtual ICollection<EntitySkillState> EntitySkillStates { get; set; }
        public virtual ICollection<EntityWidget> EntityWidgets { get; set; }
        public virtual ICollection<GeneralSetting> GeneralSettings { get; set; }
        public virtual ICollection<IntelligenceAction> IntelligenceActions { get; set; }
        public virtual ICollection<JobSearchSetting> JobSearchSettings { get; set; }
        public virtual ICollection<NetworkSetting> NetworkSettings { get; set; }
        public virtual ICollection<NotificationSubscriber> NotificationSubscribers { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<Phone> Phones { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<PostInteraction> PostInteractions { get; set; }
        public virtual ICollection<PostReplyInteraction> PostReplyInteractions { get; set; }
        public virtual ICollection<PrivacySetting> PrivacySettings { get; set; }
        public virtual ICollection<SubscriptionHistory> SubscriptionHistories { get; set; }
        public virtual ICollection<EntitySearch> EntitySearches { get; set; }
        public virtual ICollection<EntitySearch> EntitySearches1 { get; set; }
        public virtual ICollection<PostTag> PostTags { get; set; }
        public virtual ICollection<ActivityAction> ActivityActions { get; set; }
        public virtual ICollection<NetworkActivity> NetworkActivities { get; set; }
        public virtual ICollection<EntityImport> EntityImports { get; set; }
        public virtual ICollection<PostInteraction> PostInteractions1 { get; set; }
        public virtual ICollection<EntityState> EntityStates { get; set; }
        public virtual ICollection<EntityState> EntityStates1 { get; set; }
    }
}
