//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityImport
    {
        public EntityImport()
        {
            this.EntityImportContacts = new HashSet<EntityImportContact>();
        }
    
        public long ID { get; set; }
        public string ImportID { get; set; }
        public long EntityID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ImportType { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual ICollection<EntityImportContact> EntityImportContacts { get; set; }
    }
}
