//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntelligenceAction
    {
        public long ID { get; set; }
        public long EntityID { get; set; }
        public byte Type { get; set; }
        public byte Action { get; set; }
        public System.DateTime Stamp { get; set; }
    
        public virtual Entity Entity { get; set; }
    }
}
