//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSearchSetting
    {
        public long SettingID { get; set; }
        public long EntityID { get; set; }
        public Nullable<byte> JobInterestLevel { get; set; }
        public Nullable<bool> AllowToRefer { get; set; }
        public Nullable<bool> AllowOppurtunities { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> Editedate { get; set; }
    
        public virtual Entity Entity { get; set; }
    }
}
