//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_ContentType
    {
        public Master_ContentType()
        {
            this.Contents = new HashSet<Content>();
            this.Posts = new HashSet<Post>();
        }
    
        public int ContentTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PublicName { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<Content> Contents { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
}
