//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_CommentType
    {
        public Master_CommentType()
        {
            this.ContentComments = new HashSet<ContentComment>();
        }
    
        public int CommentTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] PublicName { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ContentComment> ContentComments { get; set; }
    }
}
