//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkActivity
    {
        public NetworkActivity()
        {
            this.ActivityActions = new HashSet<ActivityAction>();
            this.Notificactions = new HashSet<Notificaction>();
        }
    
        public long ID { get; set; }
        public int Type { get; set; }
        public Nullable<long> AwardID { get; set; }
        public Nullable<long> CareerHistoryID { get; set; }
        public Nullable<long> SkillID { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public Nullable<bool> ActionTaken { get; set; }
        public Nullable<int> Action { get; set; }
        public string IpAddress { get; set; }
        public long EntityID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Identifier { get; set; }
        public Nullable<long> ForEntity { get; set; }
        public Nullable<long> Years { get; set; }
    
        public virtual ICollection<ActivityAction> ActivityActions { get; set; }
        public virtual CareerHistory CareerHistory { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual EntityAwardAndCompletion EntityAwardAndCompletion { get; set; }
        public virtual EntitySkill EntitySkill { get; set; }
        public virtual ICollection<Notificaction> Notificactions { get; set; }
    }
}
