//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationSubscriber
    {
        public long SubscriberID { get; set; }
        public long NotificationID { get; set; }
        public long EntityID { get; set; }
        public bool Subscribed { get; set; }
        public byte Status { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Notificaction Notificaction { get; set; }
    }
}
