//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaction
    {
        public Notificaction()
        {
            this.NotificationSubscribers = new HashSet<NotificationSubscriber>();
        }
    
        public long NotificationID { get; set; }
        public int Type { get; set; }
        public string Text { get; set; }
        public string Url { get; set; }
        public bool Updatable { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime EditedOn { get; set; }
        public string EditedBy { get; set; }
        public Nullable<long> ReferenceID { get; set; }
        public Nullable<long> NewsID { get; set; }
        public Nullable<long> EntitySkillID { get; set; }
        public Nullable<long> AwardID { get; set; }
        public Nullable<long> ActivityID { get; set; }
        public long? ReferenceEntityID { get; set; }
    
        public virtual AppreciationAndRecommendation AppreciationAndRecommendation { get; set; }
        public virtual Post Post { get; set; }
        public virtual ICollection<NotificationSubscriber> NotificationSubscribers { get; set; }
        public virtual EntityAwardAndCompletion EntityAwardAndCompletion { get; set; }
        public virtual EntitySkill EntitySkill { get; set; }
        public virtual NetworkActivity NetworkActivity { get; set; }
    }
}
