//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectStatu
    {
        public ObjectStatu()
        {
            this.ContentComments = new HashSet<ContentComment>();
        }
    
        public byte ObjectStatusID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PublicName { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<ContentComment> ContentComments { get; set; }
    }
}
