//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationProfile
    {
        public long OrganizationProfileID { get; set; }
        public string Website { get; set; }
        public string ProfileName { get; set; }
        public string Description { get; set; }
        public string IpAddress { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EditedBy { get; set; }
        public System.DateTime EditedOn { get; set; }
        public long OrganizationID { get; set; }
        public string TagLine { get; set; }
        public string ProfileImagePath { get; set; }
        public string ProfileCoverPath { get; set; }
        public bool RequirePermission { get; set; }
        public bool Discoverable { get; set; }
    
        public virtual Organization Organization { get; set; }
    }
}
