//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.CareerHistories = new HashSet<CareerHistory>();
            this.OrganizationProfiles = new HashSet<OrganizationProfile>();
        }
    
        public long OrganizationID { get; set; }
        public string Name { get; set; }
        public Nullable<int> EstablishedYear { get; set; }
        public long EntityID { get; set; }
        public int CategoryID { get; set; }
        public string EmployeeStrength { get; set; }
        public Nullable<byte> Type { get; set; }
        public string UserID { get; set; }
        public byte? SubType { get; set; }
        
    
        public virtual ICollection<CareerHistory> CareerHistories { get; set; }
        public virtual CategoryMaster CategoryMaster { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual ICollection<OrganizationProfile> OrganizationProfiles { get; set; }
    }
}
