//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.PersonProfiles = new HashSet<PersonProfile>();
        }
    
        public long PersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string UserID { get; set; }
        public long EntityID { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual ICollection<PersonProfile> PersonProfiles { get; set; }
    }
}
