//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonProfile
    {
        public long PersonProfileID { get; set; }
        public Nullable<long> PersonID { get; set; }
        public string ProfileName { get; set; }
        public string ProfileSummary { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string IpAddress { get; set; }
        public string About { get; set; }
        public string ProfileImagePath { get; set; }
        public string ProfileHeading { get; set; }
        public Nullable<byte> NameFormat { get; set; }
        public string FormatedName { get; set; }
        public string FormatedAddress { get; set; }
        public string FormatedStudyTitle { get; set; }
        public string FormatedJobTitle { get; set; }
        public Nullable<long> ProfileIndustry { get; set; }
        public Nullable<byte> ProfileLevel { get; set; }
        public Nullable<bool> WizardFinished { get; set; }
        public Nullable<byte> WizardStep { get; set; }
        public Nullable<bool> EmailVarified { get; set; }
        public Nullable<System.DateTime> LastVarificationSent { get; set; }
        public string VarificationID { get; set; }
        public string PreviousJobTitle { get; set; }
        public string ProfileCoverPath { get; set; }
        public string ForgotPasswordHash { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
