//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public long PhoneID { get; set; }
        public long EntityID { get; set; }
        public int PhoneType { get; set; }
        public bool Active { get; set; }
        public bool Varified { get; set; }
        public string Phone1 { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime EditedOn { get; set; }
        public string EditedBy { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Master_PhoneType Master_PhoneType { get; set; }
    }
}
