//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostReply
    {
        public PostReply()
        {
            this.PostReplyInteractions = new HashSet<PostReplyInteraction>();
            this.PostReplies1 = new HashSet<PostReply>();
        }
    
        public long ID { get; set; }
        public string Reply { get; set; }
        public Nullable<long> PostID { get; set; }
        public Nullable<long> ReplyID { get; set; }
        public Nullable<byte> ReplyType { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<long> EntityID { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual ICollection<PostReplyInteraction> PostReplyInteractions { get; set; }
        public virtual ICollection<PostReply> PostReplies1 { get; set; }
        public virtual PostReply PostReply1 { get; set; }
        public byte PostType { get; set; }
    }
}
