//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Notificactions = new HashSet<Notificaction>();
            this.PostInteractions = new HashSet<PostInteraction>();
            this.PostReplies = new HashSet<PostReply>();
            this.PostTags = new HashSet<PostTag>();
        }
    
        public long ID { get; set; }
        public int PostType { get; set; }
        public Nullable<byte> SharingType { get; set; }
        public long EntityID { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string Meta { get; set; }
        public string UrlSlug { get; set; }
        public Nullable<bool> Published { get; set; }
        public string FilePath { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PublishOn { get; set; }
        public string IPAddress { get; set; }
        public Nullable<bool> AllowPublic { get; set; }
        public Nullable<long> WritterID { get; set; }
        public Nullable<long> PostID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<byte> PrivacyLevel { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> Comments { get; set; }
        public string DraftID { get; set; }
        public long? GroupEntityID { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Master_ContentType Master_ContentType { get; set; }
        public virtual ICollection<Notificaction> Notificactions { get; set; }
        public virtual ICollection<PostInteraction> PostInteractions { get; set; }
        public virtual ICollection<PostReply> PostReplies { get; set; }
        public virtual ICollection<PostTag> PostTags { get; set; }

        public ICollection<Skill> Skills { get; set; }
        public ICollection<JobTitle> JobTitles { get; set; }
    }
}
