//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostReplyInteraction
    {
        public long ID { get; set; }
        public int InteractionType { get; set; }
        public Nullable<long> ReplyID { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> EntityID { get; set; }
        public Nullable<bool> Status { get; set; }
        public string IpAddress { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual PostReply PostReply { get; set; }
    }
}
