//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrly.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDbEntities1 : DbContext
    {
        public TestDbEntities1()
            : base("name=TestDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccomplishmentState> AccomplishmentStates { get; set; }
        public DbSet<Address> Addresses { get; set; }
        public DbSet<AppreciationAndRecommendation> AppreciationAndRecommendations { get; set; }
        public DbSet<AppreciationAndRecommendationParticipant> AppreciationAndRecommendationParticipants { get; set; }
        public DbSet<AppreciationAndRecommendationSkill> AppreciationAndRecommendationSkills { get; set; }
        public DbSet<AspNetRole> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public DbSet<AspNetUser> AspNetUsers { get; set; }
        public DbSet<Association> Associations { get; set; }
        public DbSet<AwardSkill> AwardSkills { get; set; }
        public DbSet<CareerHistory> CareerHistories { get; set; }
        public DbSet<CareerHistorySkill> CareerHistorySkills { get; set; }
        public DbSet<CategoryMaster> CategoryMasters { get; set; }
        public DbSet<ChatGroup> ChatGroups { get; set; }
        public DbSet<ChatGroupMessage> ChatGroupMessages { get; set; }
        public DbSet<ChatGroupMessageListener> ChatGroupMessageListeners { get; set; }
        public DbSet<ChatGroupUser> ChatGroupUsers { get; set; }
        public DbSet<Content> Contents { get; set; }
        public DbSet<ContentComment> ContentComments { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Email> Emails { get; set; }
        public DbSet<Entity> Entities { get; set; }
        public DbSet<EntityAwardAndCompletion> EntityAwardAndCompletions { get; set; }
        public DbSet<EntityAwardParticipant> EntityAwardParticipants { get; set; }
        public DbSet<EntitySkill> EntitySkills { get; set; }
        public DbSet<EntitySkillState> EntitySkillStates { get; set; }
        public DbSet<EntityWidget> EntityWidgets { get; set; }
        public DbSet<GeneralSetting> GeneralSettings { get; set; }
        public DbSet<IntelligenceAction> IntelligenceActions { get; set; }
        public DbSet<JobSearchSetting> JobSearchSettings { get; set; }
        public DbSet<JobTitle> JobTitles { get; set; }
        public DbSet<Master_AddressType> Master_AddressType { get; set; }
        public DbSet<Master_CommentType> Master_CommentType { get; set; }
        public DbSet<Master_ContentType> Master_ContentType { get; set; }
        public DbSet<Master_EmailType> Master_EmailType { get; set; }
        public DbSet<Master_PhoneType> Master_PhoneType { get; set; }
        public DbSet<NetworkSetting> NetworkSettings { get; set; }
        public DbSet<Notificaction> Notificactions { get; set; }
        public DbSet<NotificationSubscriber> NotificationSubscribers { get; set; }
        public DbSet<ObjectStatu> ObjectStatus { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<OrganizationProfile> OrganizationProfiles { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<PersonProfile> PersonProfiles { get; set; }
        public DbSet<Phone> Phones { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<PostInteraction> PostInteractions { get; set; }
        public DbSet<PostReply> PostReplies { get; set; }
        public DbSet<PostReplyInteraction> PostReplyInteractions { get; set; }
        public DbSet<PostTag> PostTags { get; set; }
        public DbSet<PrivacySetting> PrivacySettings { get; set; }
        public DbSet<Skill> Skills { get; set; }
        public DbSet<SubscriptionHistory> SubscriptionHistories { get; set; }
        public DbSet<SubscriptionPlan> SubscriptionPlans { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<Widget> Widgets { get; set; }
        public DbSet<EntityMedia> EntityMedias { get; set; }
        public DbSet<EntitySearch> EntitySearches { get; set; }
        public DbSet<ActivityAction> ActivityActions { get; set; }
        public DbSet<NetworkActivity> NetworkActivities { get; set; }
        public DbSet<EntityImport> EntityImports { get; set; }
        public DbSet<EntityImportContact> EntityImportContacts { get; set; }
        public DbSet<EntityImportInvite> EntityImportInvites { get; set; }
        public DbSet<EntityState> EntityStates { get; set; }
    }
}
